In [17]:
import numpy as np

word_embeddings = {
    'she':    np.array([0.2, 0.9, 0.1, 0.5]),
    'likes':  np.array([0.8, 0.3, 0.7, 0.2]),
    'coffee': np.array([0.4, 0.6, 0.3, 0.9])
}

Word embeddings are vector representations of words that encode semantic meaning. Here, we define embeddings for three words, each in a 4-dimensional space. These vectors are set manually to illustrate the concept.

In [18]:
X = np.vstack([word_embeddings['she'],
               word_embeddings['likes'],
               word_embeddings['coffee']])

 stack the embeddings vertically to form the input matrix X. This matrix will be used to calculate the Query (Q), Key (K), and Value (V) matrices in subsequent steps.

In [19]:
W_q = np.array([[0.9, 0.1, 0.1, 0.1],
                [0.1, 0.9, 0.1, 0.1],
                [0.1, 0.1, 0.9, 0.1],
                [0.1, 0.1, 0.1, 0.9]])
W_k = np.array([[0.9, 0.1, 0.1, 0.1],
                [0.1, 0.9, 0.1, 0.1],
                [0.1, 0.1, 0.9, 0.1],
                [0.1, 0.1, 0.1, 0.9]])
W_v = np.array([[0.8, 0.2, 0.1, 0.1],
                [0.2, 0.8, 0.2, 0.1],
                [0.1, 0.2, 0.8, 0.1],
                [0.1, 0.1, 0.1, 0.9]])

These matrices are used to compute the Q, K, and V matrices through multiplication. Think of them as the translators that adapt our embeddings for attention. In production models, these weights are learned by the model. Here, they’re set manually to illustrate how the transformation works.

In [20]:
Q = np.dot(X, W_q)
K = np.dot(X, W_k)
V = np.dot(X, W_v)

These matrices are derived by multiplying X with each weight matrix. In a real neural network, these transformations help the model understand context.

In [21]:
scores = np.dot(Q, K.T)

The dot product of Q and the transpose of K yields the raw attention scores, measuring the relevance of each word to the others.

In [22]:
d_k = K.shape[1]
scaled_scores = scores / np.sqrt(d_k)

To avoid excessively large values that could destabilize training, we scale the scores by dividing by the square root of d_k (the dimension of the key vectors).

In [23]:
exp_scores = np.exp(scaled_scores)
attention_weights = exp_scores / exp_scores.sum(axis=1, keepdims=True)

Applying the softmax function to the scaled scores converts them into a probability distribution, highlighting the relative importance of each word.

In [24]:
output = np.dot(attention_weights, V)

The final output is computed by multiplying attention_weights by V. This output combines the information from the entire sequence in a way that considers the relevance of each word.

In [25]:
print(output)

[[0.57530294 0.70527381 0.50530294 0.64177546]
 [0.60019479 0.68822737 0.53019479 0.61916155]
 [0.58155011 0.7007833  0.51155011 0.64659215]]
